### ISSUE TITLE
travis memcached problem

### ISSUE THREAD

**Issue by yanxurui** [openresty/lua-resty-memcached#14]
Hi, sorry to bother you.

It requires to start a memcached listening at the default port(11211) when I trigger the test by `prove -r t` in local environment.
I am really confused that `.travis.yml` doesn't declare:

    services:
      - memcached

How is it possible to pass test in travis-ci environment?

**Comment by agentzh** [comment]
@yanxurui Maybe travis ci starts a default memcached server automatically? I'm not sure.

For running the tests locally, we must start a memcached server listening on the default 11211 port. I'm sure about this part.

**Comment by yanxurui** [comment]
Thank you very much.
Yes, I totally agree with you.
I made a test.
If I declare

    sudo: required
    dist: trusty
 
Then there is a default memcacahed server although the travis documentation doesn't clarify this point.
