### ISSUE TITLE
how to delete expired cache

### ISSUE THREAD

**Issue by nidepengyou** [openresty/lua-resty-memcached#17]

**Comment by agentzh** [comment]
Why? It's really about the memcached server's design, not something we could do on the client side.

**Comment by nidepengyou** [comment]
sorry. Is there any way to list all keys

**Comment by agentzh** [comment]
@nidepengyou Please do not hijack closed unrelated issues.

For general questions, you should join and post to the openresty-en mailing list instead. This place is for REAL issues only. Thank you for your cooperation. Please see

http://openresty.org/en/community.html
